### PR TITLE
ignore warning closes #49

### LINKED ISSUE #49: suppress warnings regarding SBML creation when calling yaml2sbml
When calling `yaml2petab`, one still gets the warnings
```
UserWarning: Observables are not represented in the SBML and therefore only have an effect the output, when called via yaml2PEtab
```
and similar for the conditions. When calling via `yaml2petab` this warning makes no real sense. Would like to catch + remove that in this case... :)

### PR DESCRIPTION
**Pull request by jvanhoefer**

### CODE REVIEW

**Comment by martamatos** [comment]
Stupid question, but how can i test this? Which input files should i use to run yaml2petab? xD (the example seems to be outdated in the README)

**Comment by jvanhoefer** [comment]
The CLI notebook should give a test for that :) Right now it throws the `UserWarning`.  Now it shouldn't any more :)

https://github.com/yaml2sbml-dev/yaml2sbml/blob/master/doc/examples/Lotka_Volterra_CLI/Lotka_Volterra_CLI.ipynb

**Comment by jvanhoefer** [comment]
This made me rerun the notebooks ;) As you can see here, the UserWarnings are gone now :)
https://github.com/yaml2sbml-dev/yaml2sbml/blob/feature_no_warnings/doc/examples/Lotka_Volterra_CLI/Lotka_Volterra_CLI.ipynb

**Review by martamatos — APPROVED** [review]
Thanks for linking the notebooks! :D Just to be clear, the user warnings are still active for yaml2sbml, right?
(it looks like it from the modifications)

**Pull request merged**
