### PR TITLE
add __version__ closes #56

### LINKED ISSUE #56: __version__
It would be nice, if the package had something like `yamlsbml.__version__`. 

Then you could easily check the version of the package _and_ also directly parse this in `setup.py`

### PR DESCRIPTION
**Pull request by jvanhoefer**
This should

- [x] give a `yaml2sbml.__version__`
- [x] give an automated update of the version in `setup.py` if the version is changed in `version.py`.

### CODE REVIEW

**Comment by jvanhoefer** [comment]
@martamatos Only Codacy is still open and I would ignore that (maybe even completely remove Codacy again. We have flake8, that seems enough to me ...)

**Comment by martamatos** [comment]
The second issue that codacy points out seems fair, i'm not so sure about the first one though xD
https://app.codacy.com/gh/yaml2sbml-dev/yaml2sbml/pullRequest?prid=6808586
Thoughts?

**Review by martamatos — APPROVED** [review]
Looks good to me, but i think we need to update the author list and the author email xD

**Comment by yannikschaelte** [comment]
> The second issue that codacy points out seems fair, i'm not so sure about the first one though xD
> https://app.codacy.com/gh/yaml2sbml-dev/yaml2sbml/pullRequest?prid=6808586
> Thoughts?

By some guideline, pep8 officially requires a `"""This module does that"""` line at the beginning of every file, or, as a weaker constraint, at the beginning of each module (i.e. in the `__init__` file). Just a one-line description of what's going on. Can be ignored, but does make a little sense.

Regarding the second issue: Just put `  # noqa: F401` behind that to tell linters to ignore that line.

**Comment by yannikschaelte** [comment]
> Looks good to me, but i think we need to update the author list and the author email xD

I'd just put the main contributors in there (i.e. u2), as contact e-mail whoever volunteers to take requests. Note you can also distinguish between original/main author and maintainer if the maintainer ever changes https://github.com/ICB-DCM/pyABC/blob/master/setup.cfg#L22

**Pull request merged**
