### PR TITLE
add CLI for yaml_validation closes #42

### LINKED ISSUE #42: add CLI for validate_yaml
There is currently no CLI for validating the yaml. Would be easy to add.

### PR DESCRIPTION
**Pull request by jvanhoefer**
Validation is now possible in the command line via `yaml2sbml_validate <yaml_dir>`

### CODE REVIEW

**Comment by martamatos** [comment]
Probably i'm missing something, but looking at the changes i assumed that the command was `yaml_validation <file_name>`, but when i ran it in the main folder i got `command not found`, the `yaml2sbml` command works just fine though.
Any trick i'm missing?

I was in the right branch, and i ran `pip install -e .` before trying (although i don't think i needed to do that).

**Comment by jvanhoefer** [comment]
This made me rerun the notebooks ;) As you can see here, the `UserWarning`s are gone now :)
https://github.com/yaml2sbml-dev/yaml2sbml/blob/feature_no_warnings/doc/examples/Lotka_Volterra_CLI/Lotka_Volterra_CLI.ipynb

**Comment by jvanhoefer** [comment]
I had to run `pip uninstall yaml2sbml` first, before reinstalling. Apparently the entry points are only created, if you install it for the first time... :) (Had a similar problem first). Does this solve the problem :) ?

**Comment by jvanhoefer** [comment]
Oh, I missed: The command is `yaml2sbml_validate <input_file>`

**Comment by martamatos** [comment]
Ok, made it! Thanks! :D
My only suggestion is that it says whether the yaml file is valid or not at the end, instead of just showing "Validating..."
image

Or did i miss something? (:

**Review by martamatos — APPROVED** [review]
I'll approve anyways so that you don't have to wait another 24h :)

**Comment by jvanhoefer** [comment]
I now added a nice little print statement in there :) Thx for the suggestion :)

`YAML file is valid ✅`

**Comment by martamatos** [comment]
Nice! Thanks! :D
Did you also add a statement for when the model is invalid? ;p

**Comment by jvanhoefer** [comment]
Then it throws an Error, that even says which part is currently invalid... :)

**Comment by martamatos** [comment]
Perfect! :D
Thank you!

**Pull request merged**
